[build]
  base = "client"
  publish = "build"
  command = "CI=false npm run build"

[build.environment]
  NODE_VERSION = "16"
  NPM_VERSION = "8"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
